// Maps a note's `created_by_key` (the posting app's API-key label) to its app icon.
// Icons are mirrored from the local-apps favicon registry into /public/app-icons so
// they resolve in production (Vercel can't reach the localhost:9876 source at runtime).
const APP_ICON_FILES: Record<string, string> = {
  "quick-launch": "quick-launch.png",
  "showtime": "showtime.png",
  "wallpapers": "wallpapers.png",
  "drawing": "drawing.png",
  "cheat-sheet": "cheat-sheet.png",
  "study": "study.png",
  "ai-stocks": "ai-stocks.png",
  "capture": "capture.png",
  "brushup": "brushup.png",
  "collage": "collage.png",
  "precision": "precision.png",
  "badges": "badges.png",
  "launchkit": "launchkit.png",
  "voices": "voices.png",
  "forensic": "forensic.png",
  "visual-db": "visual-db.png",
  "ai-security": "ai-security.png",
  "trends": "trends.png",
  "briefly": "briefly.png",
  "resume-plus": "resume-plus.png",
  "us-states": "us-states.png",
  "pool": "pool.png",
  "racer": "racer.png",
  "country-defense": "country-defense.png",
  "soccer": "soccer.png",
  "country-fighter": "country-fighter.png",
    "typescript": "typescript.png",
    "react": "react.png",
    "next.js": "next.js.png",
    "rust": "rust.png",
    "laravel": "laravel.png",
    "pixy": "pixy.png",
    "responsiveness": "responsiveness.png",
    "country-maker": "country-maker.png",
    "3pi": "3pi.png",
    "3pi-poc": "3pi-poc.png",
    "ai-spinner": "ai-spinner.png",
    "audit": "audit.png",
    "automations": "automations.png",
    "bheng": "bheng.png",
    "bheng2020": "bheng2020.png",
    "chrome": "chrome.svg",
    "cl-poster": "cl-poster.png",
    "claude": "claude.png",
    "claude-routine": "claude-routine.png",
    "claude-live": "claude-live.svg",
    "claude-mascot": "claude-mascot.svg",
    "clip": "clip.png",
    "countries": "countries.png",
    "geometry": "geometry.png",
    "decks": "decks.png",
    "diagrams": "diagrams.png",
    "distributor-portal": "distributor-portal.png",
    "drop": "drop.png",
    "drop-menu": "drop-menu.svg",
    "fable": "fable.png",
    "flash-cards": "flash-cards.png",
    "frames": "frames.png",
    "games": "games.png",
    "ideas": "ideas.svg",
    "kactus": "kactus.png",
    "kactus-qa": "kactus-qa.png",
    "local-apps": "local-apps.png",
    "emulator": "emulator.png",
    "math-hero": "math-hero.png",
    "automation-builder": "automation-builder.png",
    "erd": "erd.png",
    "partners": "partners.png",
    "pr-audit": "pr-audit.png",
    "skills-hub": "skills-hub.png",
    "solar-system": "solar-system.png",
    "study-timer": "study-timer.png",
    "mermaid": "mermaid.png",
    "mindmaps": "mindmaps.png",
    "moments": "moments.png",
    "norden-study": "norden-study.png",
    "periodic-table": "periodic-table.png",
    "pixel": "pixel.png",
    "pm2020": "pm2020.png",
    "pm2020-tools": "pm2020-tools.png",
    "pm2026": "pm2026.png",
    "recap": "recap.svg",
    "repo-audit": "repo-audit.png",
    "resource-audit": "resource-audit.png",
    "storage-audit": "storage-audit.png",
    "show-skills": "show-skills.png",
    "skill-architect": "skill-architect.png",
    "incident-report": "incident-report.png",
    // The yellow "job" art is retired - every job app renders the green jobs icon.
    "job": "jobs.png",
    "ai-jobs": "jobs.png",
    "jobs": "jobs.png",
    "safe": "safe.png",
    "scanme": "scanme.png",
    "score-card": "score-card.png",
    "stickies": "stickies.png",
    "flows": "flows.png",
    "think": "think.png",
    "tools": "tools.png",
    "vault": "vault.png",
    "worldcup26": "worldcup26.png",
};

// Last-resort sub-icon so a note is NEVER rendered without a source badge.
// Used when neither the posting app nor the device resolves to an icon (e.g. a
// note created directly in the browser, or an unknown attribution key).
export const DEFAULT_APP_ICON = "/app-icons/stickies.png";

// Resolve the icon path for an attribution key, or null if none exists (caller
// falls back to a text chip). Tries an exact id match first, then the leading
// segment so suffixed keys like "automations-pipeline" map to "automations".
export function appIconForKey(key: string | null | undefined): string | null {
    if (!key) return null;
    const k = key.toLowerCase();
    const file = APP_ICON_FILES[k] ?? APP_ICON_FILES[k.split("-")[0]];
    return file ? `/app-icons/${file}` : null;
}
